#!/usr/bin/env bash
# Generate a local .clangd for ESP32 Arduino IntelliSense.
# Run after clone or after updating the esp32 core: ./scripts/generate-clangd.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VARIANT="${FED4_CLANGD_VARIANT:-esp32s3}"

if [[ -z "${ARDUINO15:-}" ]]; then
  if command -v arduino-cli >/dev/null 2>&1; then
    ARDUINO15="$(arduino-cli config get directories.data 2>/dev/null || true)"
  fi
fi

if [[ -z "${ARDUINO15:-}" ]]; then
  case "$(uname -s)" in
    Darwin) ARDUINO15="${HOME}/Library/Arduino15" ;;
    MINGW*|MSYS*|CYGWIN*) ARDUINO15="${LOCALAPPDATA:-${HOME}/AppData/Local}/Arduino15" ;;
    *) ARDUINO15="${HOME}/.arduino15" ;;
  esac
fi

CORE_ROOT="${ARDUINO15}/packages/esp32/hardware/esp32"
if [[ ! -d "${CORE_ROOT}" ]]; then
  echo "error: ESP32 core not found at ${CORE_ROOT}" >&2
  echo "Install with: arduino-cli core install esp32:esp32" >&2
  exit 1
fi

VERSION=""
if command -v arduino-cli >/dev/null 2>&1; then
  VERSION="$(arduino-cli core list 2>/dev/null | awk '/^esp32:esp32[[:space:]]/ { print $2; exit }')"
fi
if [[ -z "${VERSION}" ]]; then
  VERSION="$(ls -1 "${CORE_ROOT}" | sort -V | tail -1)"
fi

CORE="${CORE_ROOT}/${VERSION}/cores/esp32"
VARIANT_DIR="${CORE_ROOT}/${VERSION}/variants/${VARIANT}"
if [[ ! -f "${CORE}/WString.h" ]]; then
  echo "error: WString.h not found under ${CORE}" >&2
  exit 1
fi
if [[ ! -d "${VARIANT_DIR}" ]]; then
  echo "error: variant '${VARIANT}' not found at ${VARIANT_DIR}" >&2
  exit 1
fi

cat > "${ROOT}/.clangd" <<EOF
# Generated by scripts/generate-clangd.sh — do not commit (.gitignore)
CompileFlags:
  Add:
    - -std=gnu++17
    - -DESP32
    - -DARDUINO=10819
    - -DARDUINO_ARCH_ESP32
    - -DARDUINO_ESP32S3_DEV
    - -I${CORE}
    - -I${VARIANT_DIR}
    - -Isrc
EOF

echo "Wrote ${ROOT}/.clangd (esp32 ${VERSION}, variant ${VARIANT})"
