#!/usr/bin/env bash
# Generate a local .clangd for ESP32 Arduino IntelliSense.
# Run after clone or after updating the esp32 core: ./scripts/generate-clangd.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VARIANT="${FED4_CLANGD_VARIANT:-esp32s3}"

if [[ -z "${ARDUINO15:-}" ]]; then
  if command -v arduino-cli >/dev/null 2>&1; then
    ARDUINO15="$(arduino-cli config get directories.data 2>/dev/null || true)"
  fi
fi

if [[ -z "${ARDUINO15:-}" ]]; then
  case "$(uname -s)" in
    Darwin) ARDUINO15="${HOME}/Library/Arduino15" ;;
    MINGW*|MSYS*|CYGWIN*) ARDUINO15="${LOCALAPPDATA:-${HOME}/AppData/Local}/Arduino15" ;;
    *) ARDUINO15="${HOME}/.arduino15" ;;
  esac
fi

USER_LIBS=""
if command -v arduino-cli >/dev/null 2>&1; then
  USER_LIBS="$(arduino-cli config get directories.user 2>/dev/null || true)/libraries"
fi
if [[ -z "${USER_LIBS}" || ! -d "${USER_LIBS}" ]]; then
  USER_LIBS="${HOME}/Documents/Arduino/libraries"
fi

CORE_ROOT="${ARDUINO15}/packages/esp32/hardware/esp32"
if [[ ! -d "${CORE_ROOT}" ]]; then
  echo "error: ESP32 core not found at ${CORE_ROOT}" >&2
  echo "Install with: arduino-cli core install esp32:esp32" >&2
  exit 1
fi

VERSION=""
if command -v arduino-cli >/dev/null 2>&1; then
  VERSION="$(arduino-cli core list 2>/dev/null | awk '/^esp32:esp32[[:space:]]/ { print $2; exit }')"
fi
if [[ -z "${VERSION}" ]]; then
  VERSION="$(ls -1 "${CORE_ROOT}" | sort -V | tail -1)"
fi

CORE="${CORE_ROOT}/${VERSION}/cores/esp32"
VARIANT_DIR="${CORE_ROOT}/${VERSION}/variants/${VARIANT}"
CORE_LIBS="${CORE_ROOT}/${VERSION}/libraries"
if [[ ! -f "${CORE}/WString.h" ]]; then
  echo "error: WString.h not found under ${CORE}" >&2
  exit 1
fi
if [[ ! -d "${VARIANT_DIR}" ]]; then
  echo "error: variant '${VARIANT}' not found at ${VARIANT_DIR}" >&2
  exit 1
fi

LIB_INCLUDES=()
add_library_dir() {
  local lib_dir="$1"
  [[ -d "${lib_dir}" ]] || return 0
  if [[ -d "${lib_dir}/src" ]]; then
    LIB_INCLUDES+=("-I${lib_dir}/src")
  elif [[ -f "${lib_dir}/library.properties" ]]; then
    LIB_INCLUDES+=("-I${lib_dir}")
  fi
}

scan_libraries_root() {
  local root="$1"
  [[ -d "${root}" ]] || return 0
  local lib_dir
  for lib_dir in "${root}"/*; do
    add_library_dir "${lib_dir}"
  done
}

scan_libraries_root "${USER_LIBS}"
scan_libraries_root "${ROOT}/.."
scan_libraries_root "${CORE_LIBS}"

{
  echo "# Generated by scripts/generate-clangd.sh — do not commit (.gitignore)"
  echo "CompileFlags:"
  echo "  Add:"
  echo "    - -std=gnu++17"
  echo "    - -DESP32"
  echo "    - -DARDUINO=10819"
  echo "    - -DARDUINO_ARCH_ESP32"
  echo "    - -DARDUINO_ESP32S3_DEV"
  echo "    - -I${CORE}"
  echo "    - -I${VARIANT_DIR}"
  echo "    - -Isrc"
  for flag in "${LIB_INCLUDES[@]}"; do
    echo "    - ${flag}"
  done
} > "${ROOT}/.clangd"

echo "Wrote ${ROOT}/.clangd (esp32 ${VERSION}, variant ${VARIANT}, ${#LIB_INCLUDES[@]} library paths)"
